openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: ''
info:
  description: This is a simple API
  version: "1.0.0"
  title: Simple Inventory API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: Articles
    description: Some list
paths:
  /api/articles:
    get:
      tags:
        - Articles
      summary: searches article
      operationId: searchArticle
      description: search articles list
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Article'
        '400':
          description: bad input parameter
  /api/articles/{id}:
    get:
      tags:
        - Articles
      summary: searches article by id
      operationId: searchArticleByID
      parameters:
       - name: id
         in: path
         description: ID of article to return
         required: true
         schema:
            type: integer
            format: int64
      description: search article by ID
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Article'
        '400':
          description: bad input parameter
  /api/articles:
    post:
      tags:
        - Articles
      summary: add new article
      operationId: addArticle
      description: Add new article or edit existing one if server gets ID
      responses:
        '201':
          description: item created
        '400':
          description: 'invalid input, object invalid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Article'
        description: Article to add
  /api/articles/{id}:
    delete:
      tags:
        - Articles
      summary: delete articles by id
      operationId: deleteArticle
      parameters:
            - name: id
              in: path
              description: ID of article to return
              required: true
              schema:
                 type: integer
                 format: int64
      description: Delete existing article by id
      responses:
        '201':
          description: item is deleted
        '400':
          description: 'invalid id'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Article'
        description: Article to delete
  /api/articles:
    delete:
      tags:
        - Articles
      summary: delete all articles in blog
      operationId: deleteArticles
      description: Delete all existing articles in blog
      responses:
        '201':
          description: items are deleted
        '400':
          description: 'invalid request'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Article'
        description: Articles to delete
components:
  schemas:
    Article:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        name:
          type: string
          example: Widget Adapter
